version: 0.8-build-{build}
image: Visual Studio 2017

build_script:
- cd C:\projects\tgui-net
- git submodule update --init --recursive
- cd build
- build.bat
- cd ..\tests
- test.bat
- cd ..
- rmdir /S /Q src\obj src\bin
- mkdir "C:\TGUI.Net 0.8-dev"
- mkdir "C:\TGUI.Net 0.8-dev\extlibs"
- xcopy src "C:\TGUI.Net 0.8-dev\src" /Y /s /i > nul
- xcopy examples "C:\TGUI.Net 0.8-dev\examples" /Y /s /i > nul
- xcopy themes "C:\TGUI.Net 0.8-dev\themes" /Y /s /i > nul
- xcopy gui-builder "C:\TGUI.Net 0.8-dev\gui-builder" /Y /s /i > nul
- xcopy lib "C:\TGUI.Net 0.8-dev\lib" /Y /s /i > nul
- xcopy extlibs\lib "C:\TGUI.Net 0.8-dev\extlibs\lib" /Y /s /i > nul
- copy README-precompiled.md "C:\TGUI.Net 0.8-dev\README.txt" /Y > nul
- 7z a -tzip C:\TGUI.Net-0.8-dev-64bit.zip "C:\TGUI.Net 0.8-dev" > nul
- cd "C:\TGUI.Net 0.8-dev\src"
- dotnet pack --configuration=Release
- appveyor PushArtifact C:\TGUI.Net-0.8-dev-64bit.zip

deploy:
- provider: GitHub
  tag: nightly_build
  release: 'Nightly build'
  description: 'Latest nightly build binary'
  draft: false
  prerelease: true
  force_update: true
  auth_token:
    secure: rVxk6OWc0JLdMi5VXVuWLAvlT1whbHHHNBPgcaJxZoYXJlwK0ixT1w1XdF5S7DBH
  on:
    branch: master
    APPVEYOR_REPO_TAG: false
