version: 0.8-build-{build}
image: Visual Studio 2017

build_script:
- cd C:\projects\tgui-net
- git submodule update --init --recursive
- cd build
- build.bat
- cd ..
- rmdir /S /Q src\obj
- mkdir "C:\TGUI.Net 0.8-dev"
- mkdir "C:\TGUI.Net 0.8-dev\lib"
- mkdir "C:\TGUI.Net 0.8-dev\extlibs"
- xcopy src "C:\TGUI.Net 0.8-dev\src" /Y /s /i > nul
- xcopy example "C:\TGUI.Net 0.8-dev\example" /Y /s /i > nul
- copy README-precompiled.md "C:\TGUI.Net 0.8-dev\README.txt" /Y > nul
- copy lib\x64\* "C:\TGUI.Net 0.8-dev\lib\" /Y > nul
- copy extlibs\lib\*.dll "C:\TGUI.Net 0.8-dev\extlibs\" /Y > nul
- 7z a -tzip TGUI.Net-0.8-dev-64bit.zip "C:\TGUI.Net 0.8-dev" > nul
- appveyor PushArtifact TGUI.Net-0.8-dev-64bit.zip

deploy:
- provider: BinTray
  username: texus
  api_key:
    secure: cSfvMUOUzComX+zv+OqpWsi4NUTZFdH/xq9hbfrqjPMyL6XFdo/Tg41IpleXdIFu
  subject: texus
  repo: generic
  package: TGUI.Net
  version: 0.8-dev-latest
  publish: true
  override: true
  explode: false
